---
# tasks file for ansible-elastic-search

- name: Get PWD
  local_action: shell pwd
  register: pwd

- name: Launch elastic-search
  docker:
    image: elasticsearch:{{ elastic_search_version }}
    name: elastic-search 
    hostname: "elastic-search"
    publish_all_ports: yes
    volumes:
      - "{{ pwd.stdout }}/elasticsearch/data:/usr/share/elasticsearch/data"
    restart_policy: always
